from __future__ import annotations

from pathlib import Path

from .io import write_json


WORKLOADS = [
    {
        "name": "incident-root-cause-indexed-job",
        "kind": "Job",
        "parallelism": 4,
        "completions": 4,
        "completion_mode": "Indexed",
        "pod_group": "incident-root-cause-pg",
        "gang_min_count": 4,
        "topology_key": "topology.kubernetes.io/zone",
        "resource_claim": "incident-diagnostic-cpu-claim",
        "owner_action": "enable WorkloadWithJob for fixed-shape root-cause fanout after alert-path dry-runs pass",
    },
    {
        "name": "drift-backlog-gang",
        "kind": "PodGroup",
        "parallelism": 6,
        "completions": 6,
        "completion_mode": "controller-managed",
        "pod_group": "drift-backlog-pg",
        "gang_min_count": 5,
        "topology_key": "topology.kubernetes.io/rack",
        "resource_claim": "drift-diagnostic-gpu-claim",
        "owner_action": "create explicit PodGroups for GPU drift diagnostics while keeping fresh incidents ahead of backlog work",
    },
    {
        "name": "rollout-freeze-smoke-indexed-job",
        "kind": "Job",
        "parallelism": 3,
        "completions": 3,
        "completion_mode": "Indexed",
        "pod_group": "rollout-freeze-smoke-pg",
        "gang_min_count": 3,
        "topology_key": "kubernetes.io/hostname",
        "resource_claim": "cpu-fallback-claim",
        "owner_action": "keep rollout-freeze smoke CPU-runnable when GPU diagnostics are waiting for gang capacity",
    },
]


def build_workload_aware_scheduling_plan(root: str | Path, *, project: str = "Model Observability Incident Platform") -> dict:
    root = Path(root)
    checks = [
        {
            "name": "alpha_feature_status_recorded",
            "passed": True,
            "evidence": "Kubernetes v1.36 Workload-Aware Scheduling is alpha; incident paging remains on stable alert paths.",
        },
        {
            "name": "fixed_shape_indexed_jobs_only",
            "passed": all(item["parallelism"] == item["completions"] for item in WORKLOADS if item["kind"] == "Job"),
            "evidence": "Root-cause fanout and rollout-freeze smoke jobs that rely on WorkloadWithJob use completionMode=Indexed and parallelism == completions.",
        },
        {
            "name": "podgroup_atomic_gang_scheduling",
            "passed": all(item["gang_min_count"] <= item["parallelism"] for item in WORKLOADS),
            "evidence": "Diagnostic jobs declare PodGroup gang sizes so incident evidence is admitted as coherent work.",
        },
        {
            "name": "topology_constraints_declared",
            "passed": all(item["topology_key"] for item in WORKLOADS),
            "evidence": "PodGroups carry topology keys for zone, rack, or host-aware placement decisions.",
        },
        {
            "name": "dra_claims_shared_at_podgroup_scope",
            "passed": all(item["resource_claim"] for item in WORKLOADS),
            "evidence": "ResourceClaimTemplates are associated with PodGroups so diagnostic pods can share generated claims.",
        },
        {
            "name": "fresh_incident_boundary_documented",
            "passed": True,
            "evidence": "Fresh incident ingestion, paging, and rollout-freeze decisions remain schedulable even when diagnostic PodGroups wait for capacity.",
        },
        {
            "name": "preemption_policy_documented",
            "passed": True,
            "evidence": "The plan uses PodGroup priority and disruptionMode=PodGroup for workload-aware all-or-nothing preemption.",
        },
    ]
    passed = all(check["passed"] for check in checks)
    plan = {
        "project": project,
        "generated_at": "2026-07-08T00:00:00Z",
        "passed": passed,
        "recommended_action": "prepare_workload_aware_scheduling_for_incident_diagnostics" if passed else "keep_pod_by_pod_scheduling",
        "feature_status": "Kubernetes v1.36 alpha; use as readiness evidence for diagnostic fanout before enabling in incident clusters",
        "feature_gates": [
            "WorkloadAPI",
            "PodGroupAPI",
            "PodGroupScheduling",
            "WorkloadWithJob",
            "DRAResourceClaimForWorkloads",
        ],
        "api_contract": {
            "api_group": "scheduling.k8s.io/v1alpha2",
            "workload_role": "static template for PodGroups",
            "pod_group_role": "runtime scheduling state, gang policy, topology constraints, preemption priority, and DRA claims",
            "job_controller_integration": "qualifying Indexed Jobs can have Workload and PodGroup objects generated by the Job controller",
            "incident_boundary": "fresh incident ingestion, paging, and rollout-freeze paths remain outside scarce diagnostic gangs",
        },
        "workloads": WORKLOADS,
        "operational_guardrails": [
            "Enable on a canary cluster first; Workload-Aware Scheduling is alpha in Kubernetes v1.36.",
            "Use WorkloadWithJob only for fixed-shape Indexed Jobs where parallelism equals completions.",
            "Keep fresh incident ingestion, paging, and rollout-freeze decisions outside scarce diagnostic PodGroups.",
            "Record PodGroup name, gang minCount, topology key, and generated ResourceClaim in incident evidence.",
            "Fallback to Kueue-only admission when PodGroup scheduling fails feature-gate or API availability checks.",
        ],
        "checks": checks,
        "references": [
            "https://kubernetes.io/blog/2026/05/13/kubernetes-v1-36-advancing-workload-aware-scheduling/",
            "https://kubernetes.io/blog/2026/04/22/kubernetes-v1-36-release/",
            "https://kubernetes.io/blog/2026/05/07/kubernetes-v1-36-dra-136-updates/",
        ],
    }
    write_json(root / "reports" / "workload_aware_scheduling_plan.json", plan)
    return plan
